// Generated by scripts/generate-navigation-glyphs.mjs from the original Kozmos navigation artwork. Edit the JSON source, never this file.
import { createPointrIcon } from "../pointr/createPointrIcon";

export const ElevatorUp = /* @__PURE__ */ createPointrIcon("ElevatorUp", [
  { d: "M2 3 L14 3 L14 21 L2 21 Z" },
  { d: "M9.5 8 C9.5 10 6.5 10 6.5 8 C6.5 6 9.5 6 9.5 8 Z" },
  { d: "M5 17 L5 13 L11 13 L11 17 M8 13 L8 19" },
  { d: "M20 19 L20 5 M17 8 L20 5 L23 8" },
]);
export const ElevatorDown = /* @__PURE__ */ createPointrIcon("ElevatorDown", [
  { d: "M2 3 L14 3 L14 21 L2 21 Z" },
  { d: "M9.5 8 C9.5 10 6.5 10 6.5 8 C6.5 6 9.5 6 9.5 8 Z" },
  { d: "M5 17 L5 13 L11 13 L11 17 M8 13 L8 19" },
  { d: "M20 5 L20 19 M17 16 L20 19 L23 16" },
]);
export const StairsUp = /* @__PURE__ */ createPointrIcon("StairsUp", [
  { d: "M2 21 L2 17 L6 17 L6 13 L10 13 L10 9 L14 9 L14 5" },
  { d: "M20 19 L20 5 M17 8 L20 5 L23 8" },
]);
export const StairsDown = /* @__PURE__ */ createPointrIcon("StairsDown", [
  { d: "M2 21 L2 17 L6 17 L6 13 L10 13 L10 9 L14 9 L14 5" },
  { d: "M20 5 L20 19 M17 16 L20 19 L23 16" },
]);
export const EscalatorUp = /* @__PURE__ */ createPointrIcon("EscalatorUp", [
  { d: "M2 17 L6 17 L12 11 L15 11 M2 21 L6 21 L12 15 L15 15" },
  { d: "M6 15 L6 11 M7.5 7 C7.5 9 4.5 9 4.5 7 C4.5 5 7.5 5 7.5 7 Z" },
  { d: "M20 19 L20 5 M17 8 L20 5 L23 8" },
]);
export const EscalatorDown = /* @__PURE__ */ createPointrIcon("EscalatorDown", [
  { d: "M2 17 L6 17 L12 11 L15 11 M2 21 L6 21 L12 15 L15 15" },
  { d: "M6 15 L6 11 M7.5 7 C7.5 9 4.5 9 4.5 7 C4.5 5 7.5 5 7.5 7 Z" },
  { d: "M20 5 L20 19 M17 16 L20 19 L23 16" },
]);
export const RampUp = /* @__PURE__ */ createPointrIcon("RampUp", [
  { d: "M2 20 L14 8 L14 20 Z" },
  { d: "M20 19 L20 5 M17 8 L20 5 L23 8" },
]);
export const RampDown = /* @__PURE__ */ createPointrIcon("RampDown", [
  { d: "M2 20 L14 8 L14 20 Z" },
  { d: "M20 5 L20 19 M17 16 L20 19 L23 16" },
]);
export const RouteEnter = /* @__PURE__ */ createPointrIcon("RouteEnter", [
  { d: "M13 3 L21 3 L21 21 L13 21 M13 3 L13 7 M13 17 L13 21" },
  { d: "M2 12 L16 12 M12 8 L16 12 L12 16" },
]);
export const RouteExit = /* @__PURE__ */ createPointrIcon("RouteExit", [
  { d: "M13 3 L21 3 L21 21 L13 21 M13 3 L13 7 M13 17 L13 21" },
  { d: "M16 12 L2 12 M6 8 L2 12 L6 16" },
]);
