import { useState } from "react";
import { Box, Button, Icon, Notice, Text } from "@kozmos-ds/react";
import type { DemoModule } from "../types";

function AboveTheResults() {
  const [expanded, setExpanded] = useState(false);
  return (
    <Box className="site-demo-column">
      <Notice
        summary="AI results may be incomplete. Check allergens with the venue."
        expanded={expanded}
        onExpandedChange={setExpanded}
      >
        These results are AI-assisted and may be incomplete or out of date. If
        you have an allergy or intolerance, confirm with the venue or its staff
        before you order.
      </Notice>
      <Text size="sm" color="muted" aria-live="polite">
        {expanded
          ? "Open. The detail was in the page all along — hidden by the hidden attribute, not by a class, so it stays hidden if the stylesheet does not load."
          : "Collapsed, it is one line worth reading on its own. Pass expanded and onExpandedChange to remember it for the session; leave them off and the notice keeps its own state."}
      </Text>
    </Box>
  );
}

function OneLineOnly() {
  return (
    <Box className="site-demo-column">
      <Notice
        tone="info"
        icon={<Icon name="stars-01" size="sm" />}
        summary="Results are generated by AI and may contain mistakes."
      />
      <Notice
        tone="warning"
        summary="The lifts between the ground and first floor are out of service until 15:00."
      />
    </Box>
  );
}

function AnEmergency() {
  const [note, setNote] = useState(
    "collapsible={false} with a critical tone: nothing is folded away and the way to act is already on screen.",
  );
  return (
    <Box className="site-demo-column">
      <Notice
        tone="critical"
        collapsible={false}
        summary="If someone’s life is in danger, call 112 now"
        action={
          <Button
            variant="destructive"
            onClick={() =>
              setNote(
                "action is a slot: a venue places the call its own way, and Kozmos never guesses how.",
              )
            }
          >
            Call 112
          </Button>
        }
      >
        Centre staff can help too. The nearest help point is beside the
        information desk on the ground floor.
      </Notice>
      <Text size="sm" color="muted" aria-live="polite">
        {note}
      </Text>
    </Box>
  );
}

export const demos: DemoModule["demos"] = [
  {
    title: "One line, with the long version a tap away",
    description:
      'summary is always visible; the children are the full wording behind the disclosure. role="status", so it is announced when results arrive without cutting across what the visitor is already hearing.',
    Component: AboveTheResults,
  },
  {
    title: "Nothing to open, in two tones",
    description:
      "With no children there is no disclosure at all. icon replaces the tone’s own; the three tones are warning, info and critical.",
    Component: OneLineOnly,
  },
  {
    title: "An emergency",
    description:
      "Help first, not a result list: collapsible={false} keeps the instruction and the way to act both on screen, because nobody should have to find a “More” link first.",
    Component: AnEmergency,
  },
];
