// Generated by scripts/build-icon-code-connect.mjs. Do not edit by hand.
//
// One connection per Icon / * component on the library's Icons page, from the
// node id recorded in figma-icons-2026-10-05-2002Z.json. A registry icon
// reaches code through Icon's name prop, so the mapping survives a change of
// which component the registry resolves that name to; a Pointr Maps - Express
// wayfinding glyph, which the registry does not name, through its icon prop.
import figma from "@figma/code-connect";
import {
  Arriving,
  CustomTransition,
  ElevatorDown,
  ElevatorUp,
  ElevatorUpAndDown,
  EscalatorDown,
  EscalatorNoDirection,
  EscalatorUp,
  FollowTheLine,
  HardLeft,
  HardRight,
  RampDown,
  RampNoDirection,
  RampUp,
  RouteEnter,
  RouteEntranceExit,
  RouteExit,
  SecurityControl,
  Shuttle,
  StairsDown,
  StairsNoDirection,
  StairsUp,
  TurnBack,
} from "@kozmos-ds/icons";
import { Icon } from "./Icon";

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1702",
  {
    example: () => <Icon name="activity" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1707",
  {
    example: () => <Icon name="alert-circle" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1712",
  {
    example: () => <Icon name="alert-triangle" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9566",
  {
    example: () => <Icon icon={Arriving} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-8850",
  {
    example: () => <Icon name="arrow-down" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1717",
  {
    example: () => <Icon name="arrow-left" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1722",
  {
    example: () => <Icon name="arrow-right" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-8859",
  {
    example: () => <Icon name="arrow-up" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1727",
  {
    example: () => <Icon name="bell-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9489",
  {
    example: () => <Icon name="bluetooth-off" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-11411",
  {
    example: () => <Icon name="bookmark" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1732",
  {
    example: () => <Icon name="building-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1737",
  {
    example: () => <Icon name="bus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1742",
  {
    example: () => <Icon name="calendar" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-11744",
  {
    example: () => <Icon name="calendar-check-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1747",
  {
    example: () => <Icon name="check" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1752",
  {
    example: () => <Icon name="chevron-down" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1757",
  {
    example: () => <Icon name="chevron-left" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1762",
  {
    example: () => <Icon name="chevron-right" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1767",
  {
    example: () => <Icon name="chevron-up" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1772",
  {
    example: () => <Icon name="clock" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-11869",
  {
    example: () => <Icon name="clock-plus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1777",
  {
    example: () => <Icon name="compass-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9569",
  {
    example: () => <Icon icon={CustomTransition} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1782",
  {
    example: () => <Icon name="download-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1787",
  {
    example: () => <Icon name="edit-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9496",
  {
    example: () => <Icon icon={ElevatorDown} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9492",
  {
    example: () => <Icon icon={ElevatorUp} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9532",
  {
    example: () => <Icon icon={ElevatorUpAndDown} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9512",
  {
    example: () => <Icon icon={EscalatorDown} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9537",
  {
    example: () => <Icon icon={EscalatorNoDirection} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9508",
  {
    example: () => <Icon icon={EscalatorUp} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-12232",
  {
    example: () => <Icon name="eye" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-12555",
  {
    example: () => <Icon name="feather" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-9784",
  {
    example: () => <Icon name="flip-backward" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9560",
  {
    example: () => <Icon icon={FollowTheLine} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-12890",
  {
    example: () => <Icon name="globe-02" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9551",
  {
    example: () => <Icon icon={HardLeft} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9554",
  {
    example: () => <Icon icon={HardRight} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13389",
  {
    example: () => <Icon name="heart" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1792",
  {
    example: () => <Icon name="home-line" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1797",
  {
    example: () => <Icon name="info-circle" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13862",
  {
    example: () => <Icon name="layout-alt-02" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13949",
  {
    example: () => <Icon name="loading-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1802",
  {
    example: () => <Icon name="lock-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13954",
  {
    example: () => <Icon name="mail-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1807",
  {
    example: () => <Icon name="map-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1812",
  {
    example: () => <Icon name="marker-pin-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1817",
  {
    example: () => <Icon name="menu-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1822",
  {
    example: () => <Icon name="minus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1827",
  {
    example: () => <Icon name="navigation-pointer-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13959",
  {
    example: () => <Icon name="phone" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1832",
  {
    example: () => <Icon name="plus" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1837",
  {
    example: () => <Icon name="qr-code-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9520",
  {
    example: () => <Icon icon={RampDown} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9543",
  {
    example: () => <Icon icon={RampNoDirection} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9516",
  {
    example: () => <Icon icon={RampUp} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1842",
  {
    example: () => <Icon name="route" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9524",
  {
    example: () => <Icon icon={RouteEnter} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9546",
  {
    example: () => <Icon icon={RouteEntranceExit} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9528",
  {
    example: () => <Icon icon={RouteExit} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1847",
  {
    example: () => <Icon name="scan" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1852",
  {
    example: () => <Icon name="search-md" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9574",
  {
    example: () => <Icon icon={SecurityControl} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1857",
  {
    example: () => <Icon name="settings-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13964",
  {
    example: () => <Icon name="share-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-13969",
  {
    example: () => <Icon name="shopping-bag-02" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9583",
  {
    example: () => <Icon icon={Shuttle} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9504",
  {
    example: () => <Icon icon={StairsDown} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9540",
  {
    example: () => <Icon icon={StairsNoDirection} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9500",
  {
    example: () => <Icon icon={StairsUp} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-10629",
  {
    example: () => <Icon name="stars-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=1923-10974",
  {
    example: () => <Icon name="switch-vertical-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1862",
  {
    example: () => <Icon name="trash-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=2151-9557",
  {
    example: () => <Icon icon={TurnBack} />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1867",
  {
    example: () => <Icon name="upload-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1872",
  {
    example: () => <Icon name="user-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1877",
  {
    example: () => <Icon name="users-01" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1882",
  {
    example: () => <Icon name="wifi" />,
  },
);

figma.connect(
  Icon,
  "https://figma.com/design/Yj4O8p6Y9h2Sa9zJVoAiVY?node-id=44-1887",
  {
    example: () => <Icon name="x-close" />,
  },
);
