// Generated by scripts/generate-navigation-glyphs.mjs. Transport artwork: packages/icons/src/owned/navigation-glyphs.json. NavigationPointer01: packages/icons/src/pointr/icons.generated.ts (Pointr node 1007:11851). Edit sources, never this file.
package com.kozmos.utils

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

internal object KozmosNavigationGlyphs {
    val ElevatorUp: ImageVector by lazy {
        ImageVector.Builder(name = "ElevatorUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 3f)
                lineTo(14f, 3f)
                lineTo(14f, 21f)
                lineTo(2f, 21f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(9.5f, 8f)
                curveTo(9.5f, 10f, 6.5f, 10f, 6.5f, 8f)
                curveTo(6.5f, 6f, 9.5f, 6f, 9.5f, 8f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(5f, 17f)
                lineTo(5f, 13f)
                lineTo(11f, 13f)
                lineTo(11f, 17f)
                moveTo(8f, 13f)
                lineTo(8f, 19f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val ElevatorDown: ImageVector by lazy {
        ImageVector.Builder(name = "ElevatorDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 3f)
                lineTo(14f, 3f)
                lineTo(14f, 21f)
                lineTo(2f, 21f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(9.5f, 8f)
                curveTo(9.5f, 10f, 6.5f, 10f, 6.5f, 8f)
                curveTo(6.5f, 6f, 9.5f, 6f, 9.5f, 8f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(5f, 17f)
                lineTo(5f, 13f)
                lineTo(11f, 13f)
                lineTo(11f, 17f)
                moveTo(8f, 13f)
                lineTo(8f, 19f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val StairsUp: ImageVector by lazy {
        ImageVector.Builder(name = "StairsUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 21f)
                lineTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(6f, 13f)
                lineTo(10f, 13f)
                lineTo(10f, 9f)
                lineTo(14f, 9f)
                lineTo(14f, 5f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val StairsDown: ImageVector by lazy {
        ImageVector.Builder(name = "StairsDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 21f)
                lineTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(6f, 13f)
                lineTo(10f, 13f)
                lineTo(10f, 9f)
                lineTo(14f, 9f)
                lineTo(14f, 5f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val EscalatorUp: ImageVector by lazy {
        ImageVector.Builder(name = "EscalatorUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(12f, 11f)
                lineTo(15f, 11f)
                moveTo(2f, 21f)
                lineTo(6f, 21f)
                lineTo(12f, 15f)
                lineTo(15f, 15f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(6f, 15f)
                lineTo(6f, 11f)
                moveTo(7.5f, 7f)
                curveTo(7.5f, 9f, 4.5f, 9f, 4.5f, 7f)
                curveTo(4.5f, 5f, 7.5f, 5f, 7.5f, 7f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val EscalatorDown: ImageVector by lazy {
        ImageVector.Builder(name = "EscalatorDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(12f, 11f)
                lineTo(15f, 11f)
                moveTo(2f, 21f)
                lineTo(6f, 21f)
                lineTo(12f, 15f)
                lineTo(15f, 15f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(6f, 15f)
                lineTo(6f, 11f)
                moveTo(7.5f, 7f)
                curveTo(7.5f, 9f, 4.5f, 9f, 4.5f, 7f)
                curveTo(4.5f, 5f, 7.5f, 5f, 7.5f, 7f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val RampUp: ImageVector by lazy {
        ImageVector.Builder(name = "RampUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 20f)
                lineTo(14f, 8f)
                lineTo(14f, 20f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val RampDown: ImageVector by lazy {
        ImageVector.Builder(name = "RampDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 20f)
                lineTo(14f, 8f)
                lineTo(14f, 20f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val RouteEnter: ImageVector by lazy {
        ImageVector.Builder(name = "RouteEnter", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(13f, 3f)
                lineTo(21f, 3f)
                lineTo(21f, 21f)
                lineTo(13f, 21f)
                moveTo(13f, 3f)
                lineTo(13f, 7f)
                moveTo(13f, 17f)
                lineTo(13f, 21f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 12f)
                lineTo(16f, 12f)
                moveTo(12f, 8f)
                lineTo(16f, 12f)
                lineTo(12f, 16f)
            }
        }.build()
    }
    val RouteExit: ImageVector by lazy {
        ImageVector.Builder(name = "RouteExit", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(13f, 3f)
                lineTo(21f, 3f)
                lineTo(21f, 21f)
                lineTo(13f, 21f)
                moveTo(13f, 3f)
                lineTo(13f, 7f)
                moveTo(13f, 17f)
                lineTo(13f, 21f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(16f, 12f)
                lineTo(2f, 12f)
                moveTo(6f, 8f)
                lineTo(2f, 12f)
                lineTo(6f, 16f)
            }
        }.build()
    }
    val NavigationPointer01: ImageVector by lazy {
        ImageVector.Builder(name = "NavigationPointer01", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(3.41345f, 10.7445f)
                curveTo(2.81811f, 10.513f, 2.52043f, 10.3972f, 2.43353f, 10.2304f)
                curveTo(2.35819f, 10.0858f, 2.35809f, 9.91354f, 2.43326f, 9.76886f)
                curveTo(2.51997f, 9.60195f, 2.8175f, 9.48584f, 3.41258f, 9.25361f)
                lineTo(20.3003f, 2.66327f)
                curveTo(20.8375f, 2.45364f, 21.1061f, 2.34883f, 21.2777f, 2.40616f)
                curveTo(21.4268f, 2.45596f, 21.5437f, 2.57292f, 21.5935f, 2.72197f)
                curveTo(21.6509f, 2.8936f, 21.5461f, 3.16219f, 21.3364f, 3.69937f)
                lineTo(14.7461f, 20.5871f)
                curveTo(14.5139f, 21.1822f, 14.3977f, 21.4797f, 14.2308f, 21.5664f)
                curveTo(14.0862f, 21.6416f, 13.9139f, 21.6415f, 13.7693f, 21.5662f)
                curveTo(13.6025f, 21.4793f, 13.4867f, 21.1816f, 13.2552f, 20.5862f)
                lineTo(10.6271f, 13.8282f)
                curveTo(10.5801f, 13.7074f, 10.5566f, 13.647f, 10.5203f, 13.5961f)
                curveTo(10.4881f, 13.551f, 10.4487f, 13.5115f, 10.4036f, 13.4794f)
                curveTo(10.3527f, 13.4431f, 10.2923f, 13.4196f, 10.1715f, 13.3726f)
                lineTo(3.41345f, 10.7445f)
                close()
            }
        }.build()
    }
}
