// Generated by scripts/generate-navigation-glyphs.mjs from the original Kozmos navigation artwork. Edit the JSON source, never this file.
package com.kozmos.utils

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

internal object KozmosNavigationGlyphs {
    val ElevatorUp: ImageVector by lazy {
        ImageVector.Builder(name = "ElevatorUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 3f)
                lineTo(14f, 3f)
                lineTo(14f, 21f)
                lineTo(2f, 21f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(9.5f, 8f)
                curveTo(9.5f, 10f, 6.5f, 10f, 6.5f, 8f)
                curveTo(6.5f, 6f, 9.5f, 6f, 9.5f, 8f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(5f, 17f)
                lineTo(5f, 13f)
                lineTo(11f, 13f)
                lineTo(11f, 17f)
                moveTo(8f, 13f)
                lineTo(8f, 19f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val ElevatorDown: ImageVector by lazy {
        ImageVector.Builder(name = "ElevatorDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 3f)
                lineTo(14f, 3f)
                lineTo(14f, 21f)
                lineTo(2f, 21f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(9.5f, 8f)
                curveTo(9.5f, 10f, 6.5f, 10f, 6.5f, 8f)
                curveTo(6.5f, 6f, 9.5f, 6f, 9.5f, 8f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(5f, 17f)
                lineTo(5f, 13f)
                lineTo(11f, 13f)
                lineTo(11f, 17f)
                moveTo(8f, 13f)
                lineTo(8f, 19f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val StairsUp: ImageVector by lazy {
        ImageVector.Builder(name = "StairsUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 21f)
                lineTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(6f, 13f)
                lineTo(10f, 13f)
                lineTo(10f, 9f)
                lineTo(14f, 9f)
                lineTo(14f, 5f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val StairsDown: ImageVector by lazy {
        ImageVector.Builder(name = "StairsDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 21f)
                lineTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(6f, 13f)
                lineTo(10f, 13f)
                lineTo(10f, 9f)
                lineTo(14f, 9f)
                lineTo(14f, 5f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val EscalatorUp: ImageVector by lazy {
        ImageVector.Builder(name = "EscalatorUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(12f, 11f)
                lineTo(15f, 11f)
                moveTo(2f, 21f)
                lineTo(6f, 21f)
                lineTo(12f, 15f)
                lineTo(15f, 15f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(6f, 15f)
                lineTo(6f, 11f)
                moveTo(7.5f, 7f)
                curveTo(7.5f, 9f, 4.5f, 9f, 4.5f, 7f)
                curveTo(4.5f, 5f, 7.5f, 5f, 7.5f, 7f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val EscalatorDown: ImageVector by lazy {
        ImageVector.Builder(name = "EscalatorDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 17f)
                lineTo(6f, 17f)
                lineTo(12f, 11f)
                lineTo(15f, 11f)
                moveTo(2f, 21f)
                lineTo(6f, 21f)
                lineTo(12f, 15f)
                lineTo(15f, 15f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(6f, 15f)
                lineTo(6f, 11f)
                moveTo(7.5f, 7f)
                curveTo(7.5f, 9f, 4.5f, 9f, 4.5f, 7f)
                curveTo(4.5f, 5f, 7.5f, 5f, 7.5f, 7f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val RampUp: ImageVector by lazy {
        ImageVector.Builder(name = "RampUp", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 20f)
                lineTo(14f, 8f)
                lineTo(14f, 20f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 19f)
                lineTo(20f, 5f)
                moveTo(17f, 8f)
                lineTo(20f, 5f)
                lineTo(23f, 8f)
            }
        }.build()
    }
    val RampDown: ImageVector by lazy {
        ImageVector.Builder(name = "RampDown", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 20f)
                lineTo(14f, 8f)
                lineTo(14f, 20f)
                close()
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(20f, 5f)
                lineTo(20f, 19f)
                moveTo(17f, 16f)
                lineTo(20f, 19f)
                lineTo(23f, 16f)
            }
        }.build()
    }
    val RouteEnter: ImageVector by lazy {
        ImageVector.Builder(name = "RouteEnter", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(13f, 3f)
                lineTo(21f, 3f)
                lineTo(21f, 21f)
                lineTo(13f, 21f)
                moveTo(13f, 3f)
                lineTo(13f, 7f)
                moveTo(13f, 17f)
                lineTo(13f, 21f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(2f, 12f)
                lineTo(16f, 12f)
                moveTo(12f, 8f)
                lineTo(16f, 12f)
                lineTo(12f, 16f)
            }
        }.build()
    }
    val RouteExit: ImageVector by lazy {
        ImageVector.Builder(name = "RouteExit", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = false).apply {
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(13f, 3f)
                lineTo(21f, 3f)
                lineTo(21f, 21f)
                lineTo(13f, 21f)
                moveTo(13f, 3f)
                lineTo(13f, 7f)
                moveTo(13f, 17f)
                lineTo(13f, 21f)
            }
            path(fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 2f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round) {
                moveTo(16f, 12f)
                lineTo(2f, 12f)
                moveTo(6f, 8f)
                lineTo(2f, 12f)
                lineTo(6f, 16f)
            }
        }.build()
    }
}
